development:
  endpoints:
    channel_management: http://simpleisbm.assetricity.com/ChannelManagementService
    provider_publication: http://simpleisbm.assetricity.com/ProviderPublicationService
    consumer_publication: http://simpleisbm.assetricity.com/ConsumerPublicationService
  options:
    log: false
    pretty_print_xml: true

test:
  endpoints:
    channel_management: http://simpleisbm.assetricity.com/ChannelManagementService
    provider_publication: http://simpleisbm.assetricity.com/ProviderPublicationService
    consumer_publication: http://simpleisbm.assetricity.com/ConsumerPublicationService
  options:
    log: false
    pretty_print_xml: true
